"""i add genres model and connect genres and books

Revision ID: 5741e3ff3f7c
Revises: 2d5b5d0c13b2
Create Date: 2026-01-22 11:38:55.492250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5741e3ff3f7c'
down_revision: Union[str, Sequence[str], None] = '2d5b5d0c13b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_genre_name'), 'genres', ['genre_name'], unique=True)
    op.create_table('book_genres',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genres')
    op.drop_index(op.f('ix_genres_genre_name'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
