"""Update user model

Revision ID: 729b69b0664f
Revises: 1e441ac6469d
Create Date: 2026-01-20 12:51:04.855084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729b69b0664f'
down_revision: Union[str, Sequence[str], None] = '1e441ac6469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__users__', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('__users__', 'image')
    # ### end Alembic commands ###
