"""a little edit

Revision ID: 89499e1d590e
Revises: c7dadeabaff8
Create Date: 2026-01-28 09:28:54.899035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89499e1d590e'
down_revision: Union[str, Sequence[str], None] = 'c7dadeabaff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_author_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_author_id_fkey'), 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
