"""Чутка изменил Ðмодель Ðкомментария

Revision ID: a3723aea97d8
Revises: 37ab916fab7c
Create Date: 2026-02-03 09:48:19.069360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3723aea97d8'
down_revision: Union[str, Sequence[str], None] = '37ab916fab7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('target_id', sa.UUID(), nullable=False))
    op.add_column('comments', sa.Column('target_type', sa.String(), nullable=False))
    op.drop_constraint(op.f('comments_book_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_book_id_fkey'), 'comments', 'books', ['book_id'], ['id'])
    op.drop_column('comments', 'target_type')
    op.drop_column('comments', 'target_id')
    # ### end Alembic commands ###
